Paginator adicionado a funcionalidade de busca
ciandt-mymusic-javers/project-myMusic pull request #10
Opened 2022-08-29 18:14 UTC by vitorlimagit

Nova PR na Develop

2022-08-29 20:13 UTC, BrunaAraujo-CIandT commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
> +                () -> musicService.findMusicsByNameOrArtists(filter, 0, 10)
Considerar a criação de uma constante para '0,10'

2022-08-29 20:14 UTC, BrunaAraujo-CIandT commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
> +        when(musicRepository.findMusicsByNameOrArtists(filter, PageRequest.of(0, 10)))
Considerar a criação de uma constante para '0,10'

2022-08-30 12:57 UTC, BrunaAraujo-CIandT requested changes

2022-08-30 13:12 UTC, sarahp-cit commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
> +                () -> musicService.findMusicsByNameOrArtists(filter, 0, 10)
Ficou acordado que esse ajuste será realizado posteriormente em uma tarefa de criação de class de constantes

2022-08-30 13:13 UTC, sarahp-cit commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
> +         assertDoesNotThrow(() -> musicService.findMusicsByNameOrArtists(filter, 0 ,10));
Ficou acordado que esse ajuste será realizado posteriormente em uma tarefa de criação de class de constantes

2022-08-30 13:13 UTC, sarahp-cit commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
> +        when(musicRepository.findMusicsByNameOrArtists(m.getName(), PageRequest.of(0, 10)))
Ficou acordado que esse ajuste será realizado posteriormente em uma tarefa de criação de class de constantes

2022-08-30 13:13 UTC, sarahp-cit commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/controller/MusicControllerTest.java
> +        given(musicService.findMusicsByNameOrArtists("s", 0, 10))
Ficou acordado que esse ajuste será realizado posteriormente em uma tarefa de criação de class de constantes

2022-08-30 13:13 UTC, sarahp-cit commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/controller/MusicControllerTest.java
> +        given(musicService.findMusicsByNameOrArtists("Nick", 0, 10))
Ficou acordado que esse ajuste será realizado posteriormente em uma tarefa de criação de class de constantes

2022-08-30 13:13 UTC, sarahp-cit commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/controller/MusicControllerTest.java
> +        given(musicService.findMusicsByNameOrArtists("Sandy", 0, 10))
Ficou acordado que esse ajuste será realizado posteriormente em uma tarefa de criação de class de constantes

2022-08-30 13:13 UTC, sarahp-cit commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
> +        when(musicRepository.findMusicsByNameOrArtists(filter, PageRequest.of(0, 10)))
Ficou acordado que esse ajuste será realizado posteriormente em uma tarefa de criação de class de constantes****

2022-08-30 13:13 UTC, sarahp-cit commented on MyMusic/src/test/java/com/ciandt/summit/bootcamp2022/service/MusicServiceTest.java
> +                musicService.findMusicsByNameOrArtists(m.getName(), 0,10));
Ficou acordado que esse ajuste será realizado posteriormente em uma tarefa de criação de class de constantes

2022-08-30 13:17 UTC, merged